2019-02-04 01:36:55,573 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575946ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 01:47:11,588 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575999ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 02:07:55,792 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576028ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 02:18:11,830 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576021ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 02:28:07,828 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 02:38:23,828 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575991ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 02:48:39,856 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576004ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 02:58:35,888 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 03:08:51,918 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576012ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 03:19:07,939 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576010ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 03:29:03,979 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576026ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 03:39:19,988 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 03:49:36,011 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576000ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 03:59:33,037 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 577012ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 04:09:50,060 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 577014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 04:20:06,089 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576007ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 04:30:02,091 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575987ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 04:37:45,113 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 423014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 04:57:00,577 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575291ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 05:07:16,597 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 05:17:32,619 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576009ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 05:27:28,645 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576017ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 05:37:44,640 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575972ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 05:57:56,668 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576007ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 06:08:12,705 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576021ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 06:18:28,751 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576032ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 06:21:58,393 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 169623ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 06:31:24,661 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 326195ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 06:42:01,002 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576322ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 07:01:57,168 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575992ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 07:12:13,202 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 07:22:09,219 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576003ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 07:32:25,228 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575987ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 07:42:41,237 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575996ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 07:52:37,242 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575994ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 08:02:53,265 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575999ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 08:13:09,303 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 08:23:05,307 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575994ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 08:33:21,345 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576022ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 08:43:37,363 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576004ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 08:53:33,383 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 09:03:49,382 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575988ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 09:24:01,389 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575982ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 09:34:17,412 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576003ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 09:44:34,414 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576979ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 09:54:30,420 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575995ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 10:04:46,440 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576013ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 10:14:43,002 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576555ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 10:24:59,008 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575989ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 10:32:15,039 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 396016ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 10:42:12,054 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 577003ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 10:52:27,086 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575027ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 11:02:23,871 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576770ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 11:12:19,092 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575211ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 11:24:46,919 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 327773ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 11:36:10,022 ERROR 84119 [-/127.0.0.1/-/25ms GET /api/user/1] nodejs.SequelizeEagerLoadingError: kepler_users_permission is not associated to kepler_users_permission!
    at Function._getIncludedAssociation (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:583:13)
    at Function._validateIncludedElement (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1570:14)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1566:8)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeEagerLoadingError"
pid: 84119
hostname: wscartdeMBP.lan

2019-02-04 11:37:35,958 ERROR 84187 [-/127.0.0.1/-/25ms GET /api/user/1] nodejs.SequelizeEagerLoadingError: kepler_users_permission is not associated to kepler_users_permission!
    at Function._getIncludedAssociation (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:583:13)
    at Function._validateIncludedElement (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1570:14)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1566:8)
    at Function.findOne (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1752:17)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeEagerLoadingError"
pid: 84187
hostname: wscartdeMBP.lan

2019-02-04 11:40:59,658 ERROR 84280 [-/127.0.0.1/-/158ms GET /api/user/1] nodejs.SequelizeDatabaseError: Not unique table/alias: 'kepler_users_permission'
    at Query.formatError (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/connection.js:80:31)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
From previous event:
    at Query.run (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/wscart/Documents/sites/node/keplerApi/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.select (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/query-interface.js:1104:27)
    at Promise.try.then.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1598:34)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1595:8)
    at Function.findOne (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1752:17)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NONUNIQ_TABLE","errno":1066,"sqlState":"42000","sqlMessage":"Not unique table/alias: 'kepler_users_permission'","sql":"SELECT `kepler_users_permission`.`id`, `kepler_users_permission`.`type`, `kepler_users_permission`.`controller`, `kepler_users_permission`.`action`, `kepler_users_permission`.`enabled`, `kepler_users_permission`.`policy`, `kepler_users_permission`.`created_at`, `kepler_users_permission`.`updated_at`, `kepler_users_permission`.`role_id`, `kepler_users_permission`.`id` AS `kepler_users_permission.id`, `kepler_users_permission`.`type` AS `kepler_users_permission.type`, `kepler_users_permission`.`controller` AS `kepler_users_permission.controller`, `kepler_users_permission`.`action` AS `kepler_users_permission.action`, `kepler_users_permission`.`enabled` AS `kepler_users_permission.enabled` FROM `kepler_users_permissions` AS `kepler_users_permission` LEFT OUTER JOIN `kepler_users_permissions` AS `kepler_users_permission` ON `kepler_users_permission`.`role_id` = `kepler_users_permission`.`id` WHERE `kepler_users_permission`.`controller` = 'UsersController' AND `kepler_users_permission`.`action` = 'index' LIMIT 1;"}
original: {"code":"ER_NONUNIQ_TABLE","errno":1066,"sqlState":"42000","sqlMessage":"Not unique table/alias: 'kepler_users_permission'","sql":"SELECT `kepler_users_permission`.`id`, `kepler_users_permission`.`type`, `kepler_users_permission`.`controller`, `kepler_users_permission`.`action`, `kepler_users_permission`.`enabled`, `kepler_users_permission`.`policy`, `kepler_users_permission`.`created_at`, `kepler_users_permission`.`updated_at`, `kepler_users_permission`.`role_id`, `kepler_users_permission`.`id` AS `kepler_users_permission.id`, `kepler_users_permission`.`type` AS `kepler_users_permission.type`, `kepler_users_permission`.`controller` AS `kepler_users_permission.controller`, `kepler_users_permission`.`action` AS `kepler_users_permission.action`, `kepler_users_permission`.`enabled` AS `kepler_users_permission.enabled` FROM `kepler_users_permissions` AS `kepler_users_permission` LEFT OUTER JOIN `kepler_users_permissions` AS `kepler_users_permission` ON `kepler_users_permission`.`role_id` = `kepler_users_permission`.`id` WHERE `kepler_users_permission`.`controller` = 'UsersController' AND `kepler_users_permission`.`action` = 'index' LIMIT 1;"}
sql: "SELECT `kepler_users_permission`.`id`, `kepler_users_permission`.`type`, `kepler_users_permission`.`controller`, `kepler_users_permission`.`action`, `kepler_users_permission`.`enabled`, `kepler_users_permission`.`policy`, `kepler_users_permission`.`created_at`, `kepler_users_permission`.`updated_at`, `kepler_users_permission`.`role_id`, `kepler_users_permission`.`id` AS `kepler_users_permission.id`, `kepler_users_permission`.`type` AS `kepler_users_permission.type`, `kepler_users_permission`.`controller` AS `kepler_users_permission.controller`, `kepler_users_permission`.`action` AS `kepler_users_permission.action`, `kepler_users_permission`.`enabled` AS `kepler_users_permission.enabled` FROM `kepler_users_permissions` AS `kepler_users_permission` LEFT OUTER JOIN `kepler_users_permissions` AS `kepler_users_permission` ON `kepler_users_permission`.`role_id` = `kepler_users_permission`.`id` WHERE `kepler_users_permission`.`controller` = 'UsersController' AND `kepler_users_permission`.`action` = 'index' LIMIT 1;"
pid: 84280
hostname: wscartdeMBP.lan

2019-02-04 11:41:01,165 ERROR 84288 [-/127.0.0.1/-/89ms GET /api/user/1] nodejs.SequelizeDatabaseError: Not unique table/alias: 'kepler_users_permission'
    at Query.formatError (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/wscart/Documents/sites/node/keplerApi/node_modules/mysql2/lib/connection.js:80:31)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
From previous event:
    at Query.run (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/wscart/Documents/sites/node/keplerApi/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.select (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/query-interface.js:1104:27)
    at Promise.try.then.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1598:34)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1595:8)
    at Function.findOne (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1752:17)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NONUNIQ_TABLE","errno":1066,"sqlState":"42000","sqlMessage":"Not unique table/alias: 'kepler_users_permission'","sql":"SELECT `kepler_users_permission`.`id`, `kepler_users_permission`.`type`, `kepler_users_permission`.`controller`, `kepler_users_permission`.`action`, `kepler_users_permission`.`enabled`, `kepler_users_permission`.`policy`, `kepler_users_permission`.`created_at`, `kepler_users_permission`.`updated_at`, `kepler_users_permission`.`role_id`, `kepler_users_permission`.`id` AS `kepler_users_permission.id`, `kepler_users_permission`.`type` AS `kepler_users_permission.type`, `kepler_users_permission`.`controller` AS `kepler_users_permission.controller`, `kepler_users_permission`.`action` AS `kepler_users_permission.action`, `kepler_users_permission`.`enabled` AS `kepler_users_permission.enabled` FROM `kepler_users_permissions` AS `kepler_users_permission` LEFT OUTER JOIN `kepler_users_permissions` AS `kepler_users_permission` ON `kepler_users_permission`.`role_id` = `kepler_users_permission`.`id` WHERE `kepler_users_permission`.`controller` = 'UsersController' AND `kepler_users_permission`.`action` = 'index' LIMIT 1;"}
original: {"code":"ER_NONUNIQ_TABLE","errno":1066,"sqlState":"42000","sqlMessage":"Not unique table/alias: 'kepler_users_permission'","sql":"SELECT `kepler_users_permission`.`id`, `kepler_users_permission`.`type`, `kepler_users_permission`.`controller`, `kepler_users_permission`.`action`, `kepler_users_permission`.`enabled`, `kepler_users_permission`.`policy`, `kepler_users_permission`.`created_at`, `kepler_users_permission`.`updated_at`, `kepler_users_permission`.`role_id`, `kepler_users_permission`.`id` AS `kepler_users_permission.id`, `kepler_users_permission`.`type` AS `kepler_users_permission.type`, `kepler_users_permission`.`controller` AS `kepler_users_permission.controller`, `kepler_users_permission`.`action` AS `kepler_users_permission.action`, `kepler_users_permission`.`enabled` AS `kepler_users_permission.enabled` FROM `kepler_users_permissions` AS `kepler_users_permission` LEFT OUTER JOIN `kepler_users_permissions` AS `kepler_users_permission` ON `kepler_users_permission`.`role_id` = `kepler_users_permission`.`id` WHERE `kepler_users_permission`.`controller` = 'UsersController' AND `kepler_users_permission`.`action` = 'index' LIMIT 1;"}
sql: "SELECT `kepler_users_permission`.`id`, `kepler_users_permission`.`type`, `kepler_users_permission`.`controller`, `kepler_users_permission`.`action`, `kepler_users_permission`.`enabled`, `kepler_users_permission`.`policy`, `kepler_users_permission`.`created_at`, `kepler_users_permission`.`updated_at`, `kepler_users_permission`.`role_id`, `kepler_users_permission`.`id` AS `kepler_users_permission.id`, `kepler_users_permission`.`type` AS `kepler_users_permission.type`, `kepler_users_permission`.`controller` AS `kepler_users_permission.controller`, `kepler_users_permission`.`action` AS `kepler_users_permission.action`, `kepler_users_permission`.`enabled` AS `kepler_users_permission.enabled` FROM `kepler_users_permissions` AS `kepler_users_permission` LEFT OUTER JOIN `kepler_users_permissions` AS `kepler_users_permission` ON `kepler_users_permission`.`role_id` = `kepler_users_permission`.`id` WHERE `kepler_users_permission`.`controller` = 'UsersController' AND `kepler_users_permission`.`action` = 'index' LIMIT 1;"
pid: 84288
hostname: wscartdeMBP.lan

2019-02-04 11:41:28,173 ERROR 84299 [-/127.0.0.1/-/26ms GET /api/user/1] nodejs.SequelizeEagerLoadingError: kepler_users_permission is not associated to kepler_users_permission!
    at Function._getIncludedAssociation (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:583:13)
    at Function._validateIncludedElement (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1570:14)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1566:8)
    at Function.findOne (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1752:17)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeEagerLoadingError"
pid: 84299
hostname: wscartdeMBP.lan

2019-02-04 11:41:29,931 ERROR 84299 [-/127.0.0.1/-/9ms GET /api/user/1] nodejs.SequelizeEagerLoadingError: kepler_users_permission is not associated to kepler_users_permission!
    at Function._getIncludedAssociation (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:583:13)
    at Function._validateIncludedElement (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1570:14)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1566:8)
    at Function.findOne (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1752:17)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeEagerLoadingError"
pid: 84299
hostname: wscartdeMBP.lan

2019-02-04 11:53:12,333 ERROR 84414 [-/127.0.0.1/-/31ms GET /api/user/1] nodejs.SequelizeEagerLoadingError: kepler_users_role is associated to kepler_users_permission using an alias. You've included an alias (role), but it does not match the alias defined in your association.
    at Function._getIncludedAssociation (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:588:17)
    at Function._validateIncludedElement (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1570:14)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1566:8)
    at Function.findOne (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1752:17)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeEagerLoadingError"
pid: 84414
hostname: wscartdeMBP.lan

2019-02-04 11:53:13,519 ERROR 84414 [-/127.0.0.1/-/5ms GET /api/user/1] nodejs.SequelizeEagerLoadingError: kepler_users_role is associated to kepler_users_permission using an alias. You've included an alias (role), but it does not match the alias defined in your association.
    at Function._getIncludedAssociation (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:588:17)
    at Function._validateIncludedElement (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1570:14)
    at processImmediate (timers.js:632:19)
From previous event:
    at Function.findAll (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1566:8)
    at Function.findOne (/Users/wscart/Documents/sites/node/keplerApi/node_modules/sequelize/lib/model.js:1752:17)
    at UserPermissionService.action (/Users/wscart/Documents/sites/node/keplerApi/app/service/permission.ts:22:43)
    at hasPermission (/Users/wscart/Documents/sites/node/keplerApi/app/middleware/permission.ts:11:54)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/app/middleware/isLogin.ts:10:13
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-graphql/app/middleware/graphql.js:64:11
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at /Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/wscart/Documents/sites/node/keplerApi/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-compose/index.js:42:32)
    at session (/Users/wscart/Documents/sites/node/keplerApi/node_modules/koa-session/index.js:41:13)
name: "SequelizeEagerLoadingError"
pid: 84414
hostname: wscartdeMBP.lan

2019-02-04 12:30:01,981 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 567293ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 12:39:58,031 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576034ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 12:49:54,055 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576012ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 13:04:07,078 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 833011ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 13:14:03,080 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575992ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 13:23:40,002 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576917ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 13:30:12,005 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 371993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 14:58:00,002 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 561559ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 15:07:55,994 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575975ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 15:12:35,017 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 259013ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 15:38:31,199 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576065ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 15:48:27,229 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576020ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 15:58:23,251 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 16:08:19,307 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576045ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 16:18:15,339 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 16:28:11,380 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576031ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 16:38:07,417 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576027ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 16:47:44,002 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576581ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 16:57:40,025 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576016ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 17:07:37,039 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 577008ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 17:17:33,038 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575994ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 17:21:59,053 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 246010ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 18:55:34,148 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 563315ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 19:05:29,171 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575011ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 19:15:25,171 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575992ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 19:25:21,203 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576026ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 19:35:17,203 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575989ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 20:05:05,232 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 575980ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 20:15:01,251 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576002ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 20:24:57,283 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 576023ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 20:34:00,304 ERROR 82992 nodejs.ClusterClientNoResponseError: client no response in 543017ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 82992
hostname: wscartdeMBP.lan

2019-02-04 21:20:37,203 ERROR 86616 [-/127.0.0.1/-/128ms POST /api/login] nodejs.TypeError: Cannot read property 'ttl' of undefined
    at ActionTokenService.create (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:14:45)
    at LoginController.login (/Users/wscart/Documents/sites/node/keplerApi/app/controller/login.ts:69:56)

pid: 86616
hostname: wscartdeMBP.lan

2019-02-04 21:22:21,755 ERROR 86698 [-/127.0.0.1/-/115ms POST /api/login] nodejs.TypeError: Cannot read property 'ttl' of undefined
    at ActionTokenService.create (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:14:45)
    at LoginController.login (/Users/wscart/Documents/sites/node/keplerApi/app/controller/login.ts:69:56)

pid: 86698
hostname: wscartdeMBP.lan

2019-02-04 21:22:32,001 ERROR 86698 [-/127.0.0.1/-/99ms POST /api/login] nodejs.TypeError: Cannot read property 'ttl' of undefined
    at ActionTokenService.create (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:14:45)
    at LoginController.login (/Users/wscart/Documents/sites/node/keplerApi/app/controller/login.ts:69:56)

pid: 86698
hostname: wscartdeMBP.lan

2019-02-04 21:31:00,068 ERROR 86828 [-/127.0.0.1/-/40ms GET /api/user/1] nodejs.TypeError: this.ctx.helper.generateMD5 is not a function
    at ActionTokenService.verifyBlack (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:92:37)
    at ActionTokenService.verify (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:30:24)

pid: 86828
hostname: wscartdeMBP.lan

2019-02-04 21:31:20,538 ERROR 86837 [-/127.0.0.1/-/21ms GET /api/user/1] nodejs.TypeError: this.ctx.helper.generateMD5 is not a function
    at ActionTokenService.verifyBlack (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:92:37)
    at ActionTokenService.verify (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:30:24)

pid: 86837
hostname: wscartdeMBP.lan

2019-02-04 21:53:03,073 ERROR 86372 nodejs.ClusterClientNoResponseError: client no response in 564607ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 86372
hostname: wscartdeMBP.lan

2019-02-04 22:03:19,094 ERROR 86372 nodejs.ClusterClientNoResponseError: client no response in 576003ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 86372
hostname: wscartdeMBP.lan

2019-02-04 22:05:40,044 ERROR 86372 nodejs.ClusterClientNoResponseError: client no response in 120943ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 86372
hostname: wscartdeMBP.lan

2019-02-04 22:09:07,445 ERROR 86372 nodejs.ClusterClientNoResponseError: client no response in 127371ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 86372
hostname: wscartdeMBP.lan

2019-02-04 22:28:23,589 ERROR 86372 nodejs.ClusterClientNoResponseError: client no response in 575960ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 86372
hostname: wscartdeMBP.lan

2019-02-04 22:38:39,637 ERROR 86372 nodejs.ClusterClientNoResponseError: client no response in 576024ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 86372
hostname: wscartdeMBP.lan

2019-02-04 22:50:02,630 ERROR 86372 nodejs.ClusterClientNoResponseError: client no response in 662979ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wscart/Documents/sites/node/keplerApi/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 86372
hostname: wscartdeMBP.lan

2019-02-04 22:51:26,409 ERROR 86960 [-/127.0.0.1/-/13ms GET /api/user/1] nodejs.TypeError: this.ctx.helper.generateMD5 is not a function
    at ActionTokenService.verifyBlack (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:92:37)
    at ActionTokenService.verify (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:30:24)

pid: 86960
hostname: wscartdeMBP.lan

2019-02-04 22:51:46,537 ERROR 86977 [-/127.0.0.1/-/12ms GET /api/user/1] nodejs.TypeError: this.ctx.helper.generateMD5 is not a function
    at ActionTokenService.verifyBlack (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:92:37)
    at ActionTokenService.verify (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:30:24)

pid: 86977
hostname: wscartdeMBP.lan

2019-02-04 22:53:45,315 ERROR 87069 [-/127.0.0.1/-/12ms GET /api/user/1] nodejs.TypeError: Cannot read property 'cache' of undefined
    at ActionTokenService.verifyBlack (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:95:36)
    at ActionTokenService.verify (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:30:24)

pid: 87069
hostname: wscartdeMBP.lan

2019-02-04 23:03:58,623 ERROR 87265 [-/127.0.0.1/-/12ms GET /api/user/1] nodejs.TypeError: this.ctx.service.cache.has is not a function
    at ActionTokenService.verifyBlack (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:95:39)
    at ActionTokenService.verify (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:30:24)

pid: 87265
hostname: wscartdeMBP.lan

2019-02-04 23:06:18,817 ERROR 87331 [-/127.0.0.1/-/14ms GET /api/user/1] nodejs.TypeError: this.ctx.abort is not a function
    at ActionTokenService.verify (/Users/wscart/Documents/sites/node/keplerApi/app/service/actionToken.ts:31:28)

pid: 87331
hostname: wscartdeMBP.lan

